# Generated by Django 3.0.7 on 2020-06-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_set', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant',
            new_name='Answer',
        ),
    ]
