# Generated by Django 3.0.7 on 2020-06-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_set', '0003_testresult_testrundetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='pics')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Middle'), (3, 'Advanced')], default=2)),
            ],
        ),
    ]
