# Generated by Django 3.0.7 on 2020-06-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_set', '0004_testlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestList',
        ),
    ]
