# Generated by Django 3.0.7 on 2020-06-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_set', '0008_auto_20200624_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultdetail',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_set.Answer'),
        ),
        migrations.AlterField(
            model_name='testresultdetail',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_set.Question'),
        ),
        migrations.AlterField(
            model_name='testresultdetail',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_result_details', to='test_set.TestResult'),
        ),
    ]
