# Generated by Django 3.0.7 on 2020-06-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_set', '0009_auto_20200624_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='avr_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
