# Generated by Django 3.0.7 on 2020-06-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_set', '0010_auto_20200624_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultdetail',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result_details', to='test_set.TestResult'),
        ),
    ]
