# Generated by Django 3.0.7 on 2020-07-15 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_set', '0014_delete_testsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultdetail',
            name='is_correct',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
